services:
  postgres-saver-db:
    image: postgres:16-alpine
    container_name: langgraph-postgres-saver
    environment:
      POSTGRES_USER: langgraph
      POSTGRES_PASSWORD: langgraph
      POSTGRES_DB: checkpoints
    ports:
      - "15432:5432"  # Using port 15432 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langgraph"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: langgraph_postgres_saver_data
